version: '3.3'

volumes:
  pg_data:
  static_value:
  media_value:

services:
  db:
    image: postgres:13
    env_file:
      - ./.env
    volumes:
      - pg_data:/var/lib/posgresql/data/

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    command: cp -r /app/build/. /static/
    volumes:
      - ../frontend/:/app/result_build/

  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_value:/var/html/static/
      - media_value:/var/html/media/

  backend:
    build:
      context: ../backend/foodgram
      dockerfile: Dockerfile
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    depends_on:
      - db
    env_file:
      - ./.env
