# Generated by Django 4.2.4 on 2023-08-13 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_recipe_image_alter_tag_color_alter_tag_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, default=1, upload_to='recipes/images/', verbose_name='Фотография рецепта'),
            preserve_default=False,
        ),
    ]
