# Generated by Django 4.2.4 on 2023-08-17 13:54

import colorfield.fields
import django.core.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_alter_recipe_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=7, samples=None, unique=True, validators=[django.core.validators.RegexValidator('^#([a-fA-F0-9]{6})', message='Используйте HEX-код для цветов')], verbose_name='Цвет тега в HEX'),
        ),
    ]
